# Generated by Django 5.0 on 2024-01-02 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=15)),
                ('percentage', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='about',
            name='percentage',
        ),
        migrations.RemoveField(
            model_name='about',
            name='skill',
        ),
    ]
