# Generated by Django 5.0 on 2024-01-05 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_skill_remove_about_percentage_remove_about_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='auth_image',
            field=models.ImageField(default='', upload_to='auth_image/'),
            preserve_default=False,
        ),
    ]
